In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy import stats

In [2]:
data = pd.read_csv("german-data-numeric-formatted.csv")

In [3]:
data.head(10)

Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
0      NaN        1        6        4       12        5        5        3   
1      NaN        2       48        2       60        1        3        2   
2      NaN        4       12        4       21        1        4        3   
3      NaN        1       42        2       79        1        4        3   
4      NaN        1       24        3       49        1        3        3   
5      NaN        4       36        2       91        5        3        3   
6      NaN        4       24        2       28        3        5        3   
7      NaN        2       36        2       69        1        3        3   
8      NaN        4       12        2       31        4        4        1   
9      NaN        2       30        4       52        1        1        4   

   Column9  Column10  ...  Column18  Column19  Column20  Column21  Column22  \
0        4         1  ...         0         1         0         0         1   
1        2         1  ...         0         1         0         0         1   
2        3         1  ...         0         1         0         0         1   
3        4         2  ...         0         0         0         0         0   
4        4         4  ...         0         1         0         0         0   
5        4         4  ...         0         1         0         0         0   
6        4         2  ...         0         1         0         0         1   
7        2         3  ...         1         1         0         1         0   
8        4         1  ...         0         1         0         0         1   
9        2         3  ...         0         1         0         0         1   

   Column23  Column24  Column25  Column26  Column27  
0         0         0         1         1       NaN  
1         0         0         1         2       NaN  
2         0         1         0         1       NaN  
3         0         0         1         1       NaN  
4         0         0         1         2       NaN  
5         0         1         0         1       NaN  
6         0         0         1         1       NaN  
7         0         0         0         1       NaN  
8         0         1         0         1       NaN  
9         0         0         0         2       NaN  

[10 rows x 27 columns]

In [4]:
data.shape

(1000, 27)

In [5]:
data['Column1'].isnull().sum()

1000

In [6]:
data['Column27'].isnull().sum()

1000

In [7]:
data = data.drop(['Column1', 'Column27'], axis = 1)

In [8]:
data

Column2  Column3  Column4  Column5  Column6  Column7  Column8  Column9  \
0          1        6        4       12        5        5        3        4   
1          2       48        2       60        1        3        2        2   
2          4       12        4       21        1        4        3        3   
3          1       42        2       79        1        4        3        4   
4          1       24        3       49        1        3        3        4   
..       ...      ...      ...      ...      ...      ...      ...      ...   
995        4       12        2       17        1        4        2        4   
996        1       30        2       39        1        3        1        4   
997        4       12        2        8        1        5        3        4   
998        1       45        2       18        1        3        3        4   
999        2       45        4       46        2        1        3        4   

     Column10  Column11  ...  Column17  Column18  Column19  Column20  \
0           1        67  ...         0         0         1         0   
1           1        22  ...         0         0         1         0   
2           1        49  ...         0         0         1         0   
3           2        45  ...         0         0         0         0   
4           4        53  ...         1         0         1         0   
..        ...       ...  ...       ...       ...       ...       ...   
995         1        31  ...         0         0         1         0   
996         2        40  ...         0         1         1         0   
997         3        38  ...         0         0         1         0   
998         4        23  ...         0         0         1         0   
999         3        27  ...         0         1         1         0   

     Column21  Column22  Column23  Column24  Column25  Column26  
0           0         1         0         0         1         1  
1           0         1         0         0         1         2  
2           0         1         0         1         0         1  
3           0         0         0         0         1         1  
4           0         0         0         0         1         2  
..        ...       ...       ...       ...       ...       ...  
995         0         1         0         1         0         1  
996         0         1         0         0         0         1  
997         0         1         0         0         1         1  
998         0         0         0         0         1         2  
999         0         1         0         0         1         1  

[1000 rows x 25 columns]

In [9]:
data.columns = ['Checking Account','Duration (months)', 'Credit History', 
                'Column5 - Credit Amount?', 'Savings Account/Bonds', 
                'Employed Since', 'Personal Status/Sex', 'Resident Since', 
                'Property', 'Age(years)', 'Other Installment Plans', 
                'Number of Existing Credits', 'Number of liable people', 
                'Telephone', 'Foreign Worker', 'Column17', 'Column18', 
                'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 
                'Column24', 'Column25', 'Cost Matrix']

In [10]:
data

Checking Account  Duration (months)  Credit History  \
0                   1                  6               4   
1                   2                 48               2   
2                   4                 12               4   
3                   1                 42               2   
4                   1                 24               3   
..                ...                ...             ...   
995                 4                 12               2   
996                 1                 30               2   
997                 4                 12               2   
998                 1                 45               2   
999                 2                 45               4   

     Column5 - Credit Amount?  Savings Account/Bonds  Employed Since  \
0                          12                      5               5   
1                          60                      1               3   
2                          21                      1               4   
3                          79                      1               4   
4                          49                      1               3   
..                        ...                    ...             ...   
995                        17                      1               4   
996                        39                      1               3   
997                         8                      1               5   
998                        18                      1               3   
999                        46                      2               1   

     Personal Status/Sex  Resident Since  Property  Age(years)  ...  Column17  \
0                      3               4         1          67  ...         0   
1                      2               2         1          22  ...         0   
2                      3               3         1          49  ...         0   
3                      3               4         2          45  ...         0   
4                      3               4         4          53  ...         1   
..                   ...             ...       ...         ...  ...       ...   
995                    2               4         1          31  ...         0   
996                    1               4         2          40  ...         0   
997                    3               4         3          38  ...         0   
998                    3               4         4          23  ...         0   
999                    3               4         3          27  ...         0   

     Column18  Column19  Column20  Column21  Column22  Column23  Column24  \
0           0         1         0         0         1         0         0   
1           0         1         0         0         1         0         0   
2           0         1         0         0         1         0         1   
3           0         0         0         0         0         0         0   
4           0         1         0         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
995         0         1         0         0         1         0         1   
996         1         1         0         0         1         0         0   
997         0         1         0         0         1         0         0   
998         0         1         0         0         0         0         0   
999         1         1         0         0         1         0         0   

     Column25  Cost Matrix  
0           1            1  
1           1            2  
2           0            1  
3           1            1  
4           1            2  
..        ...          ...  
995         0            1  
996         0            1  
997         1            1  
998         1            2  
999         1            1  

[1000 rows x 25 columns]

In [20]:
data = pd.read_csv("german-formatted.csv")

In [21]:
data

Column1  Column2 Column3 Column4  Column5 Column6 Column7  Column8  \
0       A11        6     A34     A43     1169     A65     A75        4   
1       A12       48     A32     A43     5951     A61     A73        2   
2       A14       12     A34     A46     2096     A61     A74        2   
3       A11       42     A32     A42     7882     A61     A74        2   
4       A11       24     A33     A40     4870     A61     A73        3   
..      ...      ...     ...     ...      ...     ...     ...      ...   
995     A14       12     A32     A42     1736     A61     A74        3   
996     A11       30     A32     A41     3857     A61     A73        4   
997     A14       12     A32     A43      804     A61     A75        4   
998     A11       45     A32     A43     1845     A61     A73        4   
999     A12       45     A34     A41     4576     A62     A71        3   

    Column9 Column10  ...  Column12 Column13  Column14 Column15 Column16  \
0       A93     A101  ...      A121       67      A143     A152        2   
1       A92     A101  ...      A121       22      A143     A152        1   
2       A93     A101  ...      A121       49      A143     A152        1   
3       A93     A103  ...      A122       45      A143     A153        1   
4       A93     A101  ...      A124       53      A143     A153        2   
..      ...      ...  ...       ...      ...       ...      ...      ...   
995     A92     A101  ...      A121       31      A143     A152        1   
996     A91     A101  ...      A122       40      A143     A152        1   
997     A93     A101  ...      A123       38      A143     A152        1   
998     A93     A101  ...      A124       23      A143     A153        1   
999     A93     A101  ...      A123       27      A143     A152        1   

     Column17 Column18  Column19 Column20 Column21  
0        A173        1      A192     A201        1  
1        A173        1      A191     A201        2  
2        A172        2      A191     A201        1  
3        A173        2      A191     A201        1  
4        A173        2      A191     A201        2  
..        ...      ...       ...      ...      ...  
995      A172        1      A191     A201        1  
996      A174        1      A192     A201        1  
997      A173        1      A191     A201        1  
998      A173        1      A192     A201        2  
999      A173        1      A191     A201        1  

[1000 rows x 21 columns]

In [22]:
new_names={'Column1':'Status Existing Checking Account','Column2':'Duration in month','Column3':'Credit History','Column4':'Purpose','Column5':'Credit_amount','Column6':'Savings account/bonds','Column7':'Present Employment Since','Column8':'Installment rate in percentage of disposable income','Column9':'Personal status and sex','Column10':'Other debtors/guarantors','Column11':'Present residence since','Column12':'Property','Column13':'Age in years','Column14':'Other installment plans','Column15':'Housing','Column16':'Number of existing credits at this bank','Column17':'Job','Column18':'Number of people being liable to provide maintenance for','Column19':'Telephone','Column20':'Foreign worker','Column21':'Cost Matrix'}
data.rename(columns=new_names, inplace=True)

In [23]:
data

Status Existing Checking Account  Duration in month Credit History  \
0                                A11                  6            A34   
1                                A12                 48            A32   
2                                A14                 12            A34   
3                                A11                 42            A32   
4                                A11                 24            A33   
..                               ...                ...            ...   
995                              A14                 12            A32   
996                              A11                 30            A32   
997                              A14                 12            A32   
998                              A11                 45            A32   
999                              A12                 45            A34   

    Purpose  Credit_amount Savings account/bonds Present Employment Since  \
0       A43           1169                   A65                      A75   
1       A43           5951                   A61                      A73   
2       A46           2096                   A61                      A74   
3       A42           7882                   A61                      A74   
4       A40           4870                   A61                      A73   
..      ...            ...                   ...                      ...   
995     A42           1736                   A61                      A74   
996     A41           3857                   A61                      A73   
997     A43            804                   A61                      A75   
998     A43           1845                   A61                      A73   
999     A41           4576                   A62                      A71   

     Installment rate in percentage of disposable income  \
0                                                    4     
1                                                    2     
2                                                    2     
3                                                    2     
4                                                    3     
..                                                 ...     
995                                                  3     
996                                                  4     
997                                                  4     
998                                                  4     
999                                                  3     

    Personal status and sex Other debtors/guarantors  ...  Property  \
0                       A93                     A101  ...      A121   
1                       A92                     A101  ...      A121   
2                       A93                     A101  ...      A121   
3                       A93                     A103  ...      A122   
4                       A93                     A101  ...      A124   
..                      ...                      ...  ...       ...   
995                     A92                     A101  ...      A121   
996                     A91                     A101  ...      A122   
997                     A93                     A101  ...      A123   
998                     A93                     A101  ...      A124   
999                     A93                     A101  ...      A123   

    Age in years  Other installment plans Housing  \
0             67                     A143    A152   
1             22                     A143    A152   
2             49                     A143    A152   
3             45                     A143    A153   
4             53                     A143    A153   
..           ...                      ...     ...   
995           31                     A143    A152   
996           40                     A143    A152   
997           38                     A143    A152   
998           23                     A143    A153   
999           27                 

In [ ]:
data = data.drop(data.columns[[0, 1, 2]],axis = 1)

In [24]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

data["Status Existing Checking Account"]
y = LabelBinarizer().fit_transform(data["Status Existing Checking Account"])

#y = OneHotEncoder().fit_transform(x).toarray()
print(y)
data["Status Existing Checking Account"] = y
data

# define one hot encoding
#encoder = OneHotEncoder(sparse=False)
# transform data
#onehot = encoder.fit_transform(data)
#print(onehot) 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 ...
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


Status Existing Checking Account  Duration in month Credit History  \
0                                   1                  6            A34   
1                                   0                 48            A32   
2                                   0                 12            A34   
3                                   1                 42            A32   
4                                   1                 24            A33   
..                                ...                ...            ...   
995                                 0                 12            A32   
996                                 1                 30            A32   
997                                 0                 12            A32   
998                                 1                 45            A32   
999                                 0                 45            A34   

    Purpose  Credit_amount Savings account/bonds Present Employment Since  \
0       A43           1169                   A65                      A75   
1       A43           5951                   A61                      A73   
2       A46           2096                   A61                      A74   
3       A42           7882                   A61                      A74   
4       A40           4870                   A61                      A73   
..      ...            ...                   ...                      ...   
995     A42           1736                   A61                      A74   
996     A41           3857                   A61                      A73   
997     A43            804                   A61                      A75   
998     A43           1845                   A61                      A73   
999     A41           4576                   A62                      A71   

     Installment rate in percentage of disposable income  \
0                                                    4     
1                                                    2     
2                                                    2     
3                                                    2     
4                                                    3     
..                                                 ...     
995                                                  3     
996                                                  4     
997                                                  4     
998                                                  4     
999                                                  3     

    Personal status and sex Other debtors/guarantors  ...  Property  \
0                       A93                     A101  ...      A121   
1                       A92                     A101  ...      A121   
2                       A93                     A101  ...      A121   
3                       A93                     A103  ...      A122   
4                       A93                     A101  ...      A124   
..                      ...                      ...  ...       ...   
995                     A92                     A101  ...      A121   
996                     A91                     A101  ...      A122   
997                     A93                     A101  ...      A123   
998                     A93                     A101  ...      A124   
999                     A93                     A101  ...      A123   

    Age in years  Other installment plans Housing  \
0             67                     A143    A152   
1             22                     A143    A152   
2             49                     A143    A152   
3             45                     A143    A153   
4             53                     A143    A153   
..           ...                      ...     ...   
995           31                     A143    A152   
996           40                     A143    A152   
997           38                     A143    A152   
998           23                     A143    A153   
999           27      

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                                                    Non-Null Count  Dtype 
---  ------                                                    --------------  ----- 
 0   Status Existing Checking Account                          1000 non-null   int32 
 1   Duration in month                                         1000 non-null   int64 
 2   Credit History                                            1000 non-null   object
 3   Purpose                                                   1000 non-null   object
 4   Credit_amount                                             1000 non-null   int64 
 5   Savings account/bonds                                     1000 non-null   object
 6   Present Employment Since                                  1000 non-null   object
 7   Installment rate in percentage of disposable income       1000 non-null   int64 
 8   Personal status and sex      

In [32]:
data["Status Existing Checking Account"].unique()

array([1, 0])